image:
  repository: isirajieinnocent/terraform-helm-argocd-pipeline
  tag: d90ca77
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: false
serviceAccount:
  enabled: false
autoscaling:
  enabled: false